alias mkalias="sh ~/.aliases.sh && source ~/.bash_aliases"
alias ..="cd .."
alias i="sudo apt-get install"
alias restartApache="sudo /etc/init.d/apache2 restart"
alias e="echo"
alias batinfo="acpi -V"
alias fix="echo -e \"\x1B\x28\x42\""
alias less="less -r"
alias ls="ls -G"
alias gitaddall="git add *.c *.h *.hex *.map *.mhc *.xml"
alias opensl="open -a /Applications/Sublime Text.app/"
alias kicadlock="rm ~/Library/Caches/kicad/*.lock"
alias config='/usr/bin/git --git-dir=$HOME/.myconfig/ --work-tree=$HOME'
